version: '2'
services:
 db:
    image: 'miscusi'
    build:
      context: .
    container_name: db
    volumes:
      - miscusi-MysqlDB:/var/lib/mysql   
    ports:
      - "8081:3306" 
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_PASSWORD=pass     
      - MYSQL_DATABASE=miscusi 
    
volumes:
  miscusi-MysqlDB:
  